### ISSUE TITLE
Prioritise content (or index of topics) on homepage

### ISSUE THREAD

**Issue by domchristie** [julianrubisch/better-stimulus#31]
Thanks for setting this up!

When visiting for the first time (on mobile), I was a bit unsure if there was any content, as the most prominent section is "Contributing". I wonder if it might be preferable to lead with an index of topics instead? That way we could do away with the JavaScript-y menu link (https://github.com/julianrubisch/better-stimulus/issues/29).

I'm not sure how easy the theme is to customise, but just thought I'd share. Thanks again!

**Comment by julianrubisch** [comment]
Thanks, somehow this escaped my attention. I’ve since revamped the home page a bit. Adding a TOC is certainly a good idea
